# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22df771b5c4284e45909f916c1186feaec341f058997229a7ce4f0afcf4d844fecde9e81782dc877c01d4c32dfdd4916d05af500839d7af8e9d532c62cd07e1f

test:
  secret_key_base: f1467851b99b0e628fcb9301f827bab043f18ff5f68da40919367fdba6ae5e03c82cb125bd1829ef4b17dd23bfd8bb9e3fad36cd2b07cdf1a2a319b51055ce0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
